---
- name: Clone the MTProxy
  git:
    repo: https://github.com/TelegramMessenger/MTProxy
    dest: "{{ mtproxy_compilation_directory }}"
#    version: "v{{mtproxy_version}}"
    

- name: Compile MTProxy {{ mtproxy_version }} source
  command: "make -j{{ ansible_processor_cores }}"
  args:
    chdir: "{{ mtproxy_compilation_directory }}"
    creates: "{{ mtproxy_compilation_directory }}/src/mtproxy"  
    
- name: Install MTProxy {{ mtproxy_version }} binaries
  command: make install
  args:
    chdir: "{{ mtproxy_compilation_directory }}"
    creates: "/usr/local/bin/mtproxy"

- name: Create the MTProxy config directory
  file:
    path: "{{ mtproxy_location }}"
    owner: root
    # The nobody user in nogroup needs to be able to read the config file
    group: nogroup
    # It is safe to make this directory world read only because the password
    # file and config file are not
    mode: 0755
    state: directory
    
- name: Populate the MTProxy systemd defaults
  template:
    src: MTProxy.default.j2
    dest: "/etc/default/MTProxy"
    mode: 0644

- name: Obtain a secret, used to connect to telegram servers
  shell: "curl -s https://core.telegram.org/getProxySecret > {{ mtproxy_secret_file }}"
  args:
    creates: "{{ mtproxy_secret_file }}"    

- name: Obtain current telegram configuration
  shell: "curl -s https://core.telegram.org/getProxyConfig > {{ mtproxy_proxy_multi_config }}"
  args:
    creates: "{{ mtproxy_proxy_multi_config }}"  

- import_tasks: secret.yml

- name: Run MTProxy
  shell: "/mtproto-proxy -u nobody -p 8888 -H 443 -S {{ mtproxy_secret }} --aes-pwd {{ mtproxy_secret_file }} {{ mtproxy_proxy_multi_config }} -M 1"
 

- name: Stop (init.d's) MTProxy
  systemd:
    name: MTProxy.service
    state: stopped

- name: Copy the MTProxy system unit file
  template:
    src: MTProxy.service.j2
    dest: "{{ mtproxy_systemd_service_path }}"
    mode: "0644"

- name: Enable the MTProxy service
  systemd:
    daemon_reload: yes
    name: MTProxy.service
    enabled: yes
    state: restarted
